version: "3.9"
services:
  app:
    image: node:23.4.0-alpine3.20
    working_dir: /project
    command: npm run dev
    volumes:
      - ./:/project
    ports:
      - 127.0.0.1:6700:3000
      - 127.0.0.1:6701:24678
    environment:
      NUXT_HOST: 0.0.0.0
      AIRTABLE_API_KEY:
